alias l='ls -lG'
alias ll='ls -ahlG'
alias grep='grep --color=auto'
alias brewitall='brew update && brew upgrade && brew cleanup'
alias speedtest='curl https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python'
